### ISSUE TITLE
Bot not working on Gimkit

### ISSUE THREAD

**Issue by shall2112** [ecc521/gimkit-bot#11]
Hi The bot simply only answers one question then stops

**Comment by ecc521** [comment]
Does the GimKit game have "Show Correct Answer" enabled? Currently, the bot
requires that, although PRs to fix it are welcomed.

**Comment by shall2112** [comment]
Hi yes show correct answer is enabled.
I am only 15 but studying python at school. I would be able to take on this project with some initial help

**Comment by shall2112** [comment]
?

**Comment by ecc521** [comment]
In case it helps you, I'll explain how the bot currently works.

1. Guesses at answer
2. If answer correct, store correct answer in object
3. If answer not correct, click show correct answer and store correct
answer.
4. Always pick the correct answer when the question comes up again.

What we need to do it detect when show correct answer is available. If it
is, continue as usual. If not, we need to store incorrect answers, and NOT
pick them.

The easy way to do this? Store incorrect answers instead of correct ones.
If we guess right, store the other 3 as wrong. If we guess wrong, store
that question as wrong.
